### ISSUE TITLE
NUT-04: Add optional memo for `PostMintQuoteBolt11Request`

### ISSUE THREAD

**Issue by callebtc** [cashubtc/nuts#110]
There have been multiple [requests](https://github.com/cashubtc/nutshell/issues/322) to be able to control the `memo` of an invoice. The availability of this option could depend on the backend used.

NUT-04 should have an optional `memo` field that a mint can can choose to honor (if their Lightning backend supports setting it).

**Comment by gudnuf** [comment]
Along with the option for `memo` and `expiry` it would be good to have `description_hash`. [LUD 06](https://github.com/lnurl/luds/blob/luds/06.md) requires the invoice to be generated with a description hash.

**Comment by callebtc** [comment]
> Along with the option for `memo` and `expiry` it would be good to have `description_hash`. [LUD 06](https://github.com/lnurl/luds/blob/luds/06.md) requires the invoice to be generated with a description hash.

Most backends don't allow you to set the expiry, so I'm reluctant to make this user configurable. As for the description hash, there has been an [ongoing debate](https://github.com/lnurl/luds/pull/234) whether that should be removed or not. The majority of wallets don't care about it and most backends also don't let you set it (or in the case of CLN require you to know the entire description to be able to pay).

I think memo makes sense, description hash maybe too if the need is there (although I think it doesn't matter anymore, so I'd also ignore it), but for the expiry I'm doubtful that it should be a user choice.

**Comment by gudnuf** [comment]
Agreed that `expiry` doesn't need to be in there if its not well supported.

If description hash gets removed from LUD 06, then I also don't think description hash is necessary. As it is now very few lightning address providers seem to validate it anyways.

**Comment by AngusP** [comment]
> As it is now very few lightning address providers seem to validate it anyways.

That matches my experience, I *think* there might be some that will hash the full description and check that instead if there's a `d` tag but not `h`

**Comment by thesimplekid** [comment]
I'm not sure this should added it creates an opportunity for the mint to learn more about the user and/or their intentions then is required to mint ecash which i think should be discouraged.

**Comment by callebtc** [comment]
> I'm not sure this should added it creates an opportunity for the mint to learn more about the user and/or their intentions then is required to mint ecash which i think should be discouraged.

Good point but I think it should still be optional. The mint can also read all the memos of the invoices they are paying.

**Comment by thesimplekid** [comment]
> Good point but I think it should still be optional so that mints can provide the same user experience as any other lightning wallet.

For the receiver the wallet could add a description tied to the mint quote. However, as you say that doesn't help the payee know what they're paying. So adding the optional field would allow that same experience and leave it up to the wallet to make the privacy trade off or not.

> The mint can also read all the memos of the invoices they are paying.

Right but that's a reality of lighting not a choice within the NUTs.

**Comment by minibits-cash** [comment]
Proposal to add optional description field is here:

https://github.com/minibits-cash/nuts/blob/request-desc/04.md

**Comment by callebtc** [comment]
> Proposal to add optional description field is here:

Could you open a PR and link to it here for tracking?
