### ISSUE TITLE
NUT-02: Test Vectors

### ISSUE THREAD

**Issue by clarkmoody** [cashubtc/nuts#13]
The spec should include test vectors for generating a keyset and deriving the keyset ID. A small `MAX_ORDER` would be fine to illustrate the concept.

**Comment by callebtc** [comment]
> The spec should include test vectors for generating a keyset and deriving the keyset ID. A small `MAX_ORDER` would be fine to illustrate the concept.

That would be a good idea. I can refer to the tests in nutshell here: https://github.com/cashubtc/cashu/blob/c3752fb20aeca448831c24b82b8777f2df90f303/tests/test_mint.py#L55 

And here for the individual crypto steps:

https://github.com/cashubtc/cashu/blob/main/tests/test_crypto.py


I agree, we should define vectors in this repo though.

**Comment by thunderbiscuit** [comment]
I was coming to the repo to ask about exactly this (test vectors in general, not just for NUT-02). Would be great to have a bunch here and easier to develop with than to dig into the Python/TypeScript/Go/Rust libraries for their tests (although they're all fairly easy to find).

I'm not sure how best to add those, but here's a start: #18. Let me know if you'd prefer a different format/approach. I tried to take inspiration from the [BIP-32 Test Vectors](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki).

**Comment by thunderbiscuit** [comment]
Test vectors for exactly this are being added in #27. Let me know if you'd like to add more variations.

**Comment by callebtc** [comment]
Thank you! I'll close this issue for now since we have test vectors now!
