### ISSUE TITLE
NUT-06: Mint should say what the current time is

### ISSUE THREAD

**Issue by callebtc** [cashubtc/nuts#138]
In order for users to be sure that their local clock agrees with the mint's clock, the mint should publish its current time in the info response.

**Comment by prusnak** [comment]
we should either use Unix timestamp or format returned by `JSON.stringify({'now': new Date()}) ` which is`2012-04-23T18:25:43.511Z`, rationale: https://stackoverflow.com/questions/10286204/what-is-the-right-json-date-format

**Comment by thesimplekid** [comment]
I would prefer the unix timestamp. Its what we use in other places.

**Comment by prusnak** [comment]
nutshell PR: https://github.com/cashubtc/nutshell/pull/611
