### ISSUE TITLE
NUT-06: Deprecate amount field on PostSplitRequest

### ISSUE THREAD

**Issue by gandlafbtc** [cashubtc/nuts#32]
```json
{
  "proofs": Proofs,
  "outputs": BlindedMessages,
  "amount": int //deprecate
}
```

the amount field is not necessary, since it introduces unwanted constraints. 
The client has to manage split amounts (send, return) , but the mint does not need to. The mint only needs to perform split according to the clients request.

**Comment by gandlafbtc** [comment]
```class PostSplitResponse(BaseModel):
    fst: BlindedSignatures
    snd: BlindedSignatures
```

will become 
```class PostSplitResponse(BaseModel):
    blinded: BlindedSignatures
```

and it is up to the client software to  accumulate the proofs accordingly after the split.

**Comment by thesimplekid** [comment]
This makes sense to me. I was just running into an issue where cashu.me sends outputs in the reverse order cashu-rs expects. This would solve that.

**Comment by callebtc** [comment]
> This makes sense to me. I was just running into an issue where cashu.me sends outputs in the reverse order cashu-rs expects. This would solve that. 

Could you explain how this happens? The order shouldn't be expected anywhere specifically iirc (except for the spendable check?)

**Comment by gandlafbtc** [comment]
the order matters inside the split operation: the second amount is the "send" amount, the frist amount is "return amount"

**Comment by callebtc** [comment]
The fields are 

> the order matters inside the split operation: the second amount is the "send" amount, the frist amount is "return amount"

The fields are labeled though, so there is no "order" between `fst` and `snd`. There is an order inside those fields, that's what I thought @thesimplekid is referring to.

**Comment by callebtc** [comment]
ACK.

Implemented in Nutshell mint (and wallet) in this PR: https://github.com/cashubtc/cashu/pull/263

**Comment by callebtc** [comment]
Let's please move the discussion over here and track progress in upgrading: https://github.com/cashubtc/nuts/pull/34
