### ISSUE TITLE
Uniform secret structure would prevent wallet fingerprinting

### ISSUE THREAD

**Issue by thunderbiscuit** [cashubtc/nuts#54]
The exact structure of secrets is currently left to the wallets to implement and there is no default value recommended in any NUT. Because not all client libraries build their secrets the same way, a mint can, in theory, eventually learn to fingerprint given libraries that produce certain tokens, lowering the anonymity set for those users.

It might make sense to either:
a. recommend  in one of the NUTs that client libraries use a common secret structure
b. enforce a secret size in the protocol for "simple/raw" secrets (not the secrets defined in NUT 10)

Opening this issue for discussion on these ideas.

**Comment by callebtc** [comment]
I propose we all use 32 byte hex strings as secrets!
